#!/usr/bin/env bash

# When using the exercism CLI it moves makes a folder called 'bash' and places the exercise inside.
# I do not want this bash folder.
# Therefore this script will move the exercise out of the bash folder and remove the bash folder.

# Usage
# download-exercise "<exercism-download-command>"
# OR
# bash download-exercise "<exercism-download-command>"

# Example:
# download-exercise "exercism download --exercise=two-fer --track=bash"

# since a file with no extension does not execute you can use:
# bash download-exercise "exercism download --exercise=two-fer --track=bash"

# Uncomment below line to debug the script
#set -x
ARG_COUNT="$#"

if [[ "$ARG_COUNT" != "1" ]]; then
	echo "Invalid usage."
	echo "Usage:"
      	echo "On Windows: 'bash download-exercise \"<exercism-download-command>\""
	echo "On Linux: 'download-exercise \"<exercism-download-command>\""
	exit 1
fi

COMMAND=$1
echo "Running command: $COMMAND"
$COMMAND
echo "Moving excercise files to current directory"
mv bash/* .

rm -r bash;
echo "Deleted bash folder"
exit 0

