version: "3.1"

services:
  web:
    image: yeehaw:latest
    build: .
    environment:
      # The Connection String is slightly different depending on whether its on the host or in the container.
      # Note the host name. On host machine it is localhost. In the container it is db (which is the name of the database container in the Docker network)
      DB_CONNECTION_STRING: ${DB_CONNECTION_STRING}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      APP_PORT: ${PORT}
    ports:
      - 8084:${PORT}
  db:
    image: mysql # https://hub.docker.com/_/mysql/
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: "MovieSpringDB"
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
volumes:
  mysql: